### PR TITLE
Fix English Grammar Errors

### PR DESCRIPTION
**Pull request by HollowMan6**
*I've fixed some English grammar errors for the UI.*

### CODE REVIEW

**Comment by epico** [comment]
Please include the po file changes in one separate commit!

Please update the commit message, thanks!

**Comment by HollowMan6** [comment]
I have done what you asked. @epico

**Comment by epico** [comment]
I mean two commits in this pull request.

1. first commit only contains the changes of code.

2. second commit only contains the changes of translation po files.

Sorry, I just pushed some changes into the git repo;
Please rebase your patch, thanks!

**Comment by HollowMan6** [comment]
Sorry for the misunderstanding. I have now made those changes. @epico

**Comment by epico** [comment]
No problem, the patch set is merged!

**Pull request merged**
