### PR TITLE
Support configurable opencc config

### LINKED ISSUE #154: Configurable OpenCC mode
https://github.com/libpinyin/ibus-libpinyin/blob/master/src/PYSimpTradConverter.cc#L46
currently uses the default engine, which uses 爲了 for `weile`, while the `s2tw` engine.

If you help me I can add it myself, I don't know how to expose the configuration value so that it's accessible via the ibus interface.

### PR DESCRIPTION
**Pull request by marmistrz**
Closes #154 
This should be that. Is there any way I could test it without uninstalling the distro-provided package (having the devel version side-by-side with the system package)? The real problem is the schema, gsettings won't let me create a key which is not in the schema.

### CODE REVIEW

**Comment by epico** [comment]
I think you could install the gsettings schema first.
Then kill the ibus-engine-libpinyin process, run ibus-libpinyin from git repo.
$ ./ibus-engine-libpinyin --ibus

**Comment by epico** [comment]
If the code is ready, I will begin to review the code.

**Comment by marmistrz** [comment]
It works for me locally, please start reviewing.

**Comment by epico** [comment]
Thanks for the patch! Code merged.

**Pull request merged**
