### PR TITLE
Add "All"--> setup/dicttreeview.py

### PR DESCRIPTION
**Pull request by larryw3i**

### CODE REVIEW

**Comment by epico** [comment]
Sorry, I tried your patch, but it seems not work.

**Comment by larryw3i** [comment]
> Sorry, I tried your patch, but it seems not work.

By the way, how do I compile and install it from source?

**Comment by epico** [comment]
https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by larryw3i** [comment]
> https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

It doesn't work for me if I clone source from github, hope that you add the "select all dictionaries" feature.

**Pull request closed without merging**
