### PR TITLE
Enable running setup scripts with Python 3

### PR DESCRIPTION
**Pull request by encukou**
The default uses 'python'.
To use 'python3', ./configure --with-python=python3

### CODE REVIEW

**Comment by epico** [comment]
Thanks very much for the patch!
I will merge it soon.

**Comment by encukou** [comment]
Hello,
Is there anything I can do to help merge it?

**Comment by epico** [comment]
Sorry, I am just back from a long holiday.

**Comment by epico** [comment]
Patch merged into http://github.com/epico/ibus-libpinyin,
will sync to this repo within a week.

**Pull request merged**
